
server {
    listen 443 ssl;
    server_name trungtam.mic1.edu.vn;

    ssl_certificate /etc/letsencrypt/live/trungtam.mic1.edu.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/trungtam.mic1.edu.vn/privkey.pem;

    client_max_body_size 50M;

    # Neu nguoi dung go HTTP tren cong 85, tu dong chuyen huong sang HTTPS:85
    error_page 497 =301 https://$host:85$request_uri;

    location / {
        proxy_pass         http://frontend:80;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass         http://backend:1337/api/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade     $http_upgrade;
        proxy_set_header   Connection  'upgrade';
        proxy_set_header   Host        $host;
        proxy_set_header   X-Real-IP   $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    location /uploads/ {
        proxy_pass         http://backend:1337/uploads/;
        proxy_http_version 1.1;
        proxy_set_header   Host        $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /admin/ {
        proxy_pass         http://backend:1337/admin/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade     $http_upgrade;
        proxy_set_header   Connection  'upgrade';
        proxy_set_header   Host        $host;
        proxy_cache_bypass $http_upgrade;
    }
}
