FROM node:20-alpine AS build
WORKDIR /app
COPY edumaster-frontend/package.json edumaster-frontend/package-lock.json ./
RUN npm install
COPY edumaster-frontend/ .
RUN npm run build

FROM nginx:alpine
COPY edumaster-frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
